---
- name: Begin building and configuring ansible server defined in Git.
  hosts: localhost
  connection: local
  become: yes
  tasks:

    - include_tasks: tasks/adduser.yml
    - include_tasks: tasks/collections.yml
    - include_tasks: tasks/pipinstall.yml
