- name: Install ansible collection 
  set_fact:
    PATH: "{{ lookup('env', 'PATH') }}/usr/local/bin:{{ ansible_env.PATH }}" 

- name:  
  community.general.ansible_galaxy_install:
    collections: 
      - community.general
      - ansible.posix
      - community.windows
      - community.vmware
      - community.crypto
    executable: "{{ ansible_env.PATH }}/ansible-galaxy"

