- name: ansible collection 
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin/ansible-galaxy:{{ ansible_env.PATH }}" 
  community.general.ansible_galaxy_install:
    type: collection
    name: community.vmware
    dest: /home/admin/.ansible/collections/ansible_collections/

