- name: ansible collection 
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin:{{ ansible_env.PATH }}" 

- name:  
  community.general.ansible_galaxy_install:
    type: collection
    name: community.windows

